# Generated by Django 5.0.3 on 2024-04-10 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_rename_question_event_likeevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeevent',
            old_name='question',
            new_name='event',
        ),
        migrations.AlterUniqueTogether(
            name='likeevent',
            unique_together={('user', 'event')},
        ),
    ]
