# Generated by Django 5.0.3 on 2024-04-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_rename_question_likeevent_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeEvent',
        ),
    ]
