# Generated by Django 5.0.3 on 2024-04-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='content',
            new_name='status',
        ),
    ]
