# Generated by Django 5.0.3 on 2024-04-18 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_userstatus_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='status_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
